# This workflow will run lint and many other pre-commit hooks
# https://pre-commit.com/

name: lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.8', '3.9', '3.10']
    name: Lint and pre-commit checks
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install pre-commit isort flake8==3.9.2
        pre-commit install
    - name: Run pre-commit checks including linting
      run: |
        pre-commit run --all-files
